
/** Reviewed consuming activities. Search hints, never proof of demand or seller capabilities. */
export const MATERIAL_ACTIVITIES: Readonly<Record<string, readonly string[]>> = {
  "line-pipe": ["pipeline construction", "gas transmission", "oil pipeline", "pipeline installation", "oil & gas pipelines", "cross-country pipeline", "pipeline EPC", "transmission pipeline", "gas pipeline laying", "CGD network"],
  "cs-process-pipe": ["process piping", "plant piping", "mechanical piping"],
  "ss-duplex-pipe": ["stainless piping", "stainless steel piping", "duplex piping"],
  "alloy-pipe": ["alloy piping", "power plant piping", "boiler piping"],
  octg: ["well drilling", "drilling contractor", "well completion"],
  "di-pipe": ["ductile iron pipeline installation", "water pipeline construction", "water network installation"],
  "hdpe-pipe": ["HDPE installation", "HDPE pipeline", "polyethylene pipeline", "HDPE pipe laying"],
  "grp-pipe": ["GRP installation", "GRE piping", "fiberglass pipeline", "GRP pipe installation"],
  "pvc-pipe": ["PVC pipe installation", "plumbing installation", "drainage installation"],
  "bw-fittings": ["process piping fabrication", "pipeline installation", "pipe spool fabrication"],
  "forged-fittings": ["high pressure piping", "process piping fabrication", "socket weld piping"],
  flanges: ["piping fabrication", "pipeline installation", "process plant piping"],
  "induction-bends": ["pipeline construction", "pipeline bending", "gas transmission pipeline"],
  spools: ["piping installation", "process plant construction", "mechanical piping installation"],
  "gate-globe-check": ["industrial valve installation", "process piping", "water network installation"],
  "ball-valves": ["gas pipeline installation", "process piping", "pipeline valve installation"],
  "butterfly-valves": ["water network installation", "HVAC installation", "industrial valve installation"],
  "control-relief-valves": ["process instrumentation", "process plant construction", "pressure safety systems"],
  "coating-materials": ["pipeline coating", "pipe coating application", "pipeline corrosion protection"],
  "field-joint-coating": ["field joint coating application", "pipeline construction", "pipeline coating"],
  "cathodic-protection": ["cathodic protection installation", "pipeline corrosion protection", "cathodic protection systems"],
  paints: ["industrial painting", "protective coating application", "steel structure painting"],
  "stud-bolts": ["piping fabrication", "steel structure erection", "mechanical equipment installation"],
  gaskets: ["process piping installation", "flanged piping", "plant maintenance"],
  "welding-consumables": ["steel fabrication", "pipeline welding", "structural welding"],
  abrasives: ["abrasive blasting", "surface preparation", "metal fabrication"],
  "structural-steel": ["structural steel fabrication", "steel structure erection", "steel fabrication"],
  plates: ["pressure vessel fabrication", "shipbuilding", "storage tank fabrication", "pressure vessel manufacturing", "vessel construction", "ship repair", "boiler manufacturing", "heavy fabrication", "steel plate fabrication"],
  rebar: ["reinforced concrete construction", "rebar installation", "reinforcement fixing"],
  "gratings-handrails": ["industrial platform construction", "steel structure erection", "pipe support installation"],
  cables: ["power cable installation", "electrical contracting", "power distribution construction", "cable laying", "electrical installation", "HV cable installation", "EHV cable installation", "HVDC cable installation", "11kV to 400kV cable installation", "substation cabling", "underground cabling"],
  "cable-trays": ["cable tray installation", "electrical installation", "MEP installation"],
  instruments: ["process instrumentation installation", "instrumentation installation", "process automation"],
  insulation: ["thermal insulation installation", "industrial insulation", "pipe insulation"],
  pumps: ["pumping station construction", "pump installation", "water treatment plant construction"],
};

/** Exact user-input aliases. Ambiguous short tokens never silently choose a catalogue item. */
export const INPUT_ALIASES: Readonly<Record<string, readonly string[]>> = {
  "line-pipe": ["pipeline", "pipeline pipe", "line pipes", "api 5l", "gas transmission pipe"],
  "cs-process-pipe": ["carbon steel piping", "carbon steel pipes", "process pipe", "a106", "astm a106", "a53"],
  "ss-duplex-pipe": ["stainless steel pipe", "stainless piping", "stainless steel piping", "ss pipe", "duplex pipe", "duplex piping", "astm a312"],
  "alloy-pipe": ["alloy pipe", "chrome moly pipe", "astm a335"],
  octg: ["octg", "casing and tubing", "well casing", "api 5ct"],
  "di-pipe": ["di pipe", "ductile iron pipes", "k9 pipe"],
  "hdpe-pipe": ["hdpe", "hdpe pipes", "pe100 pipe", "polyethylene pipe"],
  "grp-pipe": ["grp pipe", "gre pipe", "fiberglass pipe", "fibreglass pipe"],
  "pvc-pipe": ["pvc pipe", "upvc", "upvc pipe", "cpvc pipe"],
  "bw-fittings": ["butt weld fittings", "buttweld fittings", "pipe fittings", "b16.9"],
  "forged-fittings": ["socket weld fittings", "threaded fittings", "b16.11"],
  flanges: ["flange", "pipe flanges", "b16.5"],
  "induction-bends": ["induction bends", "hot bends", "insulating joints"],
  spools: ["pipe spools", "prefabricated piping spools"],
  "gate-globe-check": ["gate valve", "gate valves", "globe valve", "check valve", "check valves"],
  "ball-valves": ["ball valve", "pipeline ball valves"],
  "butterfly-valves": ["butterfly valve"],
  "control-relief-valves": ["control valve", "relief valve", "safety relief valves", "psv"],
  "coating-materials": ["pipe coating materials", "3lpe", "3lpp", "fbe powder"],
  "field-joint-coating": ["heat shrink sleeves", "field joint coating"],
  "cathodic-protection": ["anodes for cathodic protection", "iccp"],
  paints: ["industrial paint", "protective paint", "epoxy paint"],
  "stud-bolts": ["stud bolt", "stud bolts and nuts"],
  gaskets: ["gasket", "spiral wound gaskets", "rtj gasket"],
  "welding-consumables": ["welding wire", "welding electrodes", "welding rods", "welding flux"],
  abrasives: ["cutting discs", "grinding discs", "blasting grit"],
  "structural-steel": ["steel structure", "structural sections", "steel beams", "steel channels"],
  plates: ["steel plate", "steel sheets", "hot rolled coil"],
  rebar: ["reinforcing bar", "reinforcement steel", "tmt bars", "tmt bar"],
  "gratings-handrails": ["gratings", "steel gratings", "handrails", "pipe supports"],
  cables: ["power cables", "power cable", "control cables", "electrical wiring", "electrical cables", "armoured cable", "copper wiring"],
  "cable-trays": ["cable tray", "cable ladders", "cable ladder"],
  instruments: ["pressure gauges", "pressure gauge", "flow meters", "flow meter", "temperature gauges"],
  insulation: ["thermal insulation", "mineral wool", "rock wool", "pipe insulation"],
  pumps: ["pump", "water pumps", "process pumps"],
};

// Free-text interpretation and the material check live in ./material-catalogue (resolveMaterial).
