"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type KeyboardEvent } from "react";
import { ArrowRight, Building2, ExternalLink, Mail, MapPin, Network, Users } from "lucide-react";
import type { Opportunity } from "@/mvp/opportunities";
import { CONTACT_ROLES, activityLabel, journey, uniquePublishedContacts, verifiedProspect } from "@/mvp/opportunities/workflow";
import type { BuyerView, EvidenceDrawerView } from "@/mvp/buyers/types";
import type { LeadDetail } from "@/mvp/types";
import type { DemoEmailInfo } from "@/mvp/email/config";
import type { EnrichmentView } from "@/mvp/enrichment";
import { apiJson } from "../api-client";
import { formatDateTime } from "../labels";
import { marketName } from "@/mvp/config/markets";
import { ContactEnrichment } from "./contact-enrichment";
import { ConversationTimeline } from "../outreach/conversation-timeline";
import { SupplyChainExplorer } from "../buyers/supply-chain-explorer";
import { ProofList } from "../search/buyer-sections";
import { BuyerHistorySection, ProjectSection, SupplyChainSection } from "../lead-sections";
import { EvidenceProvider } from "../evidence";
import {EvidenceDrawer,parseDrawerTarget,drawerKey,type DrawerTarget} from '../evidence/evidence-drawer';
import {SourceCards} from '../evidence/source-card';
import {WorkspaceChainTables} from '../tables/workspace-chain-tables';
import { OpportunityRail, namedContacts, WORKSPACE_TABS, type ContactPoint, type WorkspaceTab } from "./workspace-rail";

interface Props {
  opportunity: Opportunity; buyer: BuyerView; returnTo: string; demoEmail: DemoEmailInfo;
  events: { id: number; body: string; created_at: string }[];
  drafts: { id: string; subject: string | null; body: string | null; delivery_state: string | null; delivery_recipient: string | null; campaign_status: string | null; created_at: string }[];
  points: ContactPoint[]; enrichment?: EnrichmentView; detail?: LeadDetail | null;
  initialTab?:WorkspaceTab; calendarResult?:string; demoOutreach?:boolean; initialEvidenceOpen?:string; evidenceView?:EvidenceDrawerView|null;
}

/** Restores company intelligence and supply-chain depth in the search-scoped lead workflow. */
export function OpportunityWorkspace({ opportunity, buyer, returnTo, events, drafts, points, demoEmail, enrichment, detail,initialTab,calendarResult,demoOutreach=false,initialEvidenceOpen='',evidenceView }: Props) {
  // An unnamed project does not negate evidence of an award in legacy records.
  const o={...opportunity,buying_reason:opportunity.buying_reason.replace("Company-level services evidence; no awarded project established.","Company-level opportunity; no specific project name established.")};
  const router = useRouter();
  const [tab, setTab] = useState<WorkspaceTab>(initialTab??"overview");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [evidenceTarget,setEvidenceTarget]=useState<DrawerTarget|null>(()=>parseDrawerTarget(initialEvidenceOpen,o.run_id));
  const [summary, setSummary] = useState<string|null>(null);
  const [ownerName, setOwner] = useState(o.owner_name);
  const [nextAction, setAction] = useState(o.next_action);
  const [followUpAt, setFollowUp] = useState(o.follow_up_at?.slice(0,16) ?? "");
  const demoJourney=demoOutreach&&!o.is_sample;
  const progress = demoJourney?{stage:o.sent?'Follow email & meeting progress':'Automatic product-fit check & demo selection',action:'View automatic workflow',step:o.sent?2:0}:journey(o.qualification, o.validated_emails, o.sent, o.is_sample);
  const journeySteps=demoJourney?['Automatic product-fit check','Demo email queued','Introduction accepted','Buyer replies','Meeting booked']:['Check product fit','Contacts / enrichment','Demo email','Conversation','Meeting'];
  const proof = buyer.proof.filter(p => o.evidence_ids.includes(p.evidenceId));
  // The legacy situation resolver defaults unidentified work to pipelines. Never
  // carry that guessed specialism into a source-backed material opportunity.
  const businessActivity=evidenceView!==undefined?evidenceView?.header.whatTheyDo??'':o.discovery_version
    ? buyer.role==='subcontractor'?'Subcontractor':buyer.role==='fabricator'?'Fabricator':buyer.role==='epc_contractor'?'Engineering contractor':buyer.role==='manufacturer'?'Manufacturer · potential input buyer':buyer.role==='distributor'?'Potential channel customer':'Material-consuming company'
    : buyer.whatTheyDo;
  const people = namedContacts(buyer, enrichment);
  const related = (buyer.chain ?? []).filter(c => c.identified && c.companyId && c.companyId !== buyer.companyId);
  const companyContacts = uniquePublishedContacts(enrichment?.companyContacts?.length ? enrichment.companyContacts : o.public_contacts ?? []);
  const projectDetail = detail?.project?.id === o.project_id ? detail : null;
  const patch = async (body: object) => {
    setBusy(true); setError(null); setSaved(false);
    try { await apiJson(`/api/mvp/opportunities/${o.id}`, { method: "PATCH", body }); setSaved(true); router.refresh(); }
    catch (err) { setError(err instanceof Error ? err.message : "Could not save."); }
    finally { setBusy(false); }
  };
  function selectTab(next: WorkspaceTab) { setTab(next); }
  function tabKey(event: KeyboardEvent<HTMLButtonElement>, index: number) {
    const next = event.key === "ArrowRight" ? (index + 1) % WORKSPACE_TABS.length : event.key === "ArrowLeft" ? (index + WORKSPACE_TABS.length - 1) % WORKSPACE_TABS.length : event.key === "Home" ? 0 : event.key === "End" ? WORKSPACE_TABS.length - 1 : null;
    if (next === null) return;
    event.preventDefault(); selectTab(WORKSPACE_TABS[next].id); document.getElementById(`tab-${WORKSPACE_TABS[next].id}`)?.focus();
  }
  const trigger=evidenceView?.header.trigger;
  const proofIds=new Set(evidenceView?.sources.flatMap(s=>s.quotes.map(q=>q.evidenceId))??[]);
  const workspaceEvidence=evidenceView!==undefined?Object.fromEntries(Object.entries(detail?.evidence??{}).filter(([id])=>proofIds.has(id))):detail?.evidence??{};
  const workCountry=evidenceView!==undefined?evidenceView?.header.operatingCountry:o.project_country??o.country;
  const hqCountry=evidenceView!==undefined?evidenceView?.header.hqCountry:o.country;
  const why=evidenceView!==undefined?evidenceView?.why??'':o.buying_reason;
  const activityQuote=evidenceView!==undefined?evidenceView?.sources.flatMap(s=>s.quotes).find(q=>q.highlight===o.activity_quote)?.highlight:o.activity_quote;
  function openProof(){setEvidenceTarget({opportunityId:o.id,leadId:o.lead_id,run:o.run_id});const url=new URL(window.location.href);url.searchParams.set('open',o.id);window.history.replaceState(window.history.state,'',url.pathname+url.search);}
  return <EvidenceProvider evidence={workspaceEvidence} onOpenEvidence={openProof}><div className="flex min-w-0 flex-col gap-5 pb-8">
    <div className="flex flex-wrap items-center justify-between gap-2"><Link href={returnTo} className="text-sm font-semibold text-[var(--accent-2)]">← Back to filtered CRM results</Link><Link href={`/find?run=${encodeURIComponent(o.run_id)}`} className="text-xs text-[var(--text-2)] hover:underline">From search: {o.keyword}</Link></div>
    <header className="flex flex-wrap items-start justify-between gap-4">
      <div className="flex min-w-0 flex-1 basis-full items-start gap-3 sm:basis-auto"><span className="mt-1 grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent-2)]"><Building2 size={24} aria-hidden /></span><div className="min-w-0"><p className="eyebrow">Lead workspace · {o.project_name ? "Project-linked opportunity" : "Company-level opportunity"}</p><h1 className="mt-1 text-2xl font-bold leading-tight tracking-tight">{o.name}</h1><p className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-sm text-[var(--text-2)]">{workCountry ? <span className="inline-flex items-center gap-1"><MapPin size={14} aria-hidden />{marketName(workCountry)}</span> : null}{businessActivity ? <span>{businessActivity}</span> : null}<span>Product: {o.product_name}</span></p></div></div>
      <button className="btn btn-primary" onClick={() => selectTab("conversation")}><Mail size={15} aria-hidden />Email & meeting progress</button>
    </header>
    <section className="card p-4" aria-label="Trigger"><p className="eyebrow">Trigger · {trigger?.kind==='capability'?'Capability only':trigger?.kind??'Not established'}</p><h2 className="mt-2 font-semibold">{trigger?.title??''}</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-3">{[['When',trigger?.date],['Value',trigger?.valueText],['Project',trigger?.projectName],['Owner',trigger?.ownerName],['Work country',trigger?.country?marketName(trigger.country):null]].map(([label,value])=><div key={label}><dt className="text-xs text-[var(--muted)]">{label}</dt><dd>{value??''}</dd></div>)}</dl>{evidenceView?<button className="mt-3 text-sm font-semibold text-[var(--accent-2)] underline" onClick={openProof}>View {evidenceView.sources.length} verified sources</button>:null}</section>
    <section aria-label="What we can sell them" className="rounded-xl border border-[var(--accent)] bg-[var(--accent-soft)] p-4"><p className="eyebrow">What we can sell them</p><h2 className="mt-1 text-lg font-bold text-[var(--accent-2)]">{o.product_name}</h2>{tab!=='conversation'?<p className="mt-1 text-sm">{evidenceView!==undefined?evidenceView?.why??'':o.buying_reason}</p>:null}<p className="mt-2 text-xs text-[var(--text-2)]">Product from this search only. Potential need is not a confirmed order; specifications and quantity need discussion.</p></section>
    {tab!=='conversation'?<>
    <section aria-label="Material fit and current activity" className="card p-4"><div className="flex flex-wrap gap-2"><span className="chip">{o.material_fit_kind === "explicit" ? "Explicit material use" : "Potential material application"}</span><span className="chip">{activityLabel(o.activity_status)}</span></div><dl className="mt-3 text-xs"><dt className="text-[var(--text-2)]">Activity date</dt><dd className="mt-1">{evidenceView!==undefined?trigger?.date??'':o.activity_date?.slice(0,10)??''}</dd></dl>{activityQuote ? <blockquote className="mt-3 border-l-2 border-[var(--line)] pl-3 text-sm">{activityQuote}</blockquote> : null}<p className="mt-2 text-xs text-[var(--text-2)]">Capability evidence is not proof of a current purchase. Missing dates remain blank.</p>{o.discovery_version && o.priority_components && Object.keys(o.priority_components).length ? <details className="mt-3 text-xs"><summary className="cursor-pointer font-semibold">Why this priority? · {o.fit_score}/100</summary><dl className="mt-2 grid gap-2 sm:grid-cols-2">{Object.entries(o.priority_components).filter(([,value])=>typeof value === "number").map(([key,value])=><div key={key}><dt className="text-[var(--text-2)]">{key.replace(/_/g," ")}</dt><dd>{value}</dd></div>)}</dl><p className="mt-2">Priority orders research. It is not a purchase probability or contact validation.</p></details> : null}</section>
    {companyContacts.length ? <section aria-label="Published company contact details" className="card flex flex-wrap items-center gap-x-5 gap-y-2 p-4 text-sm"><p className="font-semibold">Published company contacts</p>{[...new Map(companyContacts.map(c=>[`${c.kind}:${c.value}`,c])).values()].filter(c=>/^https?:\/\//i.test(c.source_url)).slice(0,4).map(c=><a key={`${c.kind}:${c.value}`} href={c.source_url} target="_blank" rel="noreferrer" className="break-all text-[var(--accent-2)] underline">{c.value}</a>)}<button className="text-xs font-semibold text-[var(--accent-2)]" onClick={()=>selectTab("contacts")}>View sources & all contacts →</button><p className="basis-full text-xs text-[var(--text-2)]">Company switchboards/inboxes, not verified personal contacts.</p></section> : null}
    {o.is_sample ? <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Sample data — not a real buyer or validated contact.</p> : null}
    <section className="card p-4" aria-label="Lead journey"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Next step</p><h2 className="mt-1 text-base font-bold">{progress.stage}</h2></div><button className="btn btn-secondary btn-sm" onClick={() => selectTab(demoJourney||o.sent ? "conversation" : o.qualification !== "approved" ? "overview" : "contacts")}>{progress.action}<ArrowRight size={14} aria-hidden /></button></div><ol className="mt-3 grid gap-2 text-xs sm:grid-cols-5">{journeySteps.map((step,i) => <li key={step}><button onClick={() => selectTab(i === 0 ? "overview" : i === 1&&!demoJourney ? "contacts" : "conversation")} aria-current={i === progress.step ? "step" : undefined} className={`w-full rounded-lg border p-2 text-left ${i === progress.step ? "border-[var(--accent)] bg-[var(--accent-soft)] font-semibold" : "border-[var(--line)] text-[var(--text-2)] hover:bg-[var(--subtle)]"}`}>{i + 1}. {step}</button></li>)}</ol></section>
    </>:null}
    {error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}{saved ? <p role="status" className="text-sm text-green-700">Saved successfully.</p> : null}
    <div className="grid min-w-0 items-start gap-5 lg:grid-cols-[minmax(0,1fr)_280px] xl:grid-cols-[minmax(0,1fr)_300px]">
      <div className="min-w-0">
        <div role="tablist" aria-label="Lead workspace" className="mb-5 flex flex-wrap gap-1 border-b border-[var(--line)]">{WORKSPACE_TABS.map((item,index) => <button key={item.id} role="tab" aria-selected={tab === item.id} tabIndex={tab === item.id ? 0 : -1} aria-controls={`panel-${item.id}`} id={`tab-${item.id}`} onKeyDown={e => tabKey(e,index)} className={`inline-flex items-center gap-1.5 border-b-2 px-3 py-3 text-xs font-semibold transition-colors ${tab === item.id ? "border-[var(--accent)] text-[var(--accent-2)]" : "border-transparent text-[var(--text-2)] hover:text-[var(--foreground)]"}`} onClick={() => selectTab(item.id)}><item.icon size={14} aria-hidden />{item.name}</button>)}</div>
        <div role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`} tabIndex={0} className="flex min-w-0 flex-col gap-4 outline-none">
          {tab === "overview" ? <>
            <div className="grid gap-3 sm:grid-cols-3"><section className="card p-4"><p className="eyebrow">What we can offer</p><h2 className="mt-2 font-bold text-[var(--accent-2)]">{o.product_name}</h2><p className="mt-2 text-xs text-[var(--text-2)]">Only the product from this search. Specifications and current demand need confirmation.</p></section><section className="card p-4"><p className="eyebrow">Buying team</p><h2 className="mt-2 font-bold">{people.length} named contacts</h2><p className="mt-2 text-xs text-[var(--text-2)]">{buyer.team.length} role slots · {o.validated_emails} eligible validated emails</p><button className="mt-2 text-xs font-semibold text-[var(--accent-2)]" onClick={() => selectTab("contacts")}>Explore buying team →</button></section><section className="card p-4"><p className="eyebrow">Related companies</p><h2 className="mt-2 font-bold">{related.length} identified</h2><p className="mt-2 text-xs text-[var(--text-2)]">Subcontractors, suppliers and their contacts stay linked to this lead.</p><button className="mt-2 text-xs font-semibold text-[var(--accent-2)]" onClick={() => selectTab("chain")}>Explore supply chain →</button></section></div>
            <section className="card p-5" aria-label="Buyer fit and evidence"><p className="eyebrow">Why this company might buy</p><h2 className="mt-2 text-lg font-bold">Potential need for {o.product_name}</h2><p className="mt-2 text-sm leading-relaxed">{why}</p><p className="mt-2 text-xs text-[var(--text-2)]">Potential fit is not a confirmed purchase. No price, quantity or buying window is invented.</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy || o.qualification === "approved"} className="btn btn-primary btn-sm" onClick={() => void patch({qualification:"approved"})}>Confirm product buyer fit</button><button disabled={busy || o.qualification === "rejected"} className="btn btn-secondary btn-sm" onClick={() => void patch({qualification:"rejected"})}>Not relevant for this product</button></div><div className="mt-5 border-t border-[var(--line)] pt-4"><h3 className="mb-2 text-sm font-semibold">Supporting evidence · {evidenceView!==undefined?evidenceView?.sources.length??0:proof.length} source(s)</h3>{evidenceView!==undefined?<SourceCards sources={evidenceView?.sources??[]}/>:proof.length ? <ProofList proof={proof.map(p => ({...p,url:p.url && /^https?:\/\//i.test(p.url) ? p.url : null}))} /> : <p className="text-sm text-[var(--text-2)]">No source quotes stored for this search.</p>}</div></section>
            {projectDetail ? <ProjectSection detail={projectDetail} /> : <section className="card p-5" aria-label="Project context"><p className="eyebrow">Project context</p><h2 className="mt-2 font-bold">{o.project_name || ""}</h2><p className="mt-2 text-sm text-[var(--text-2)]">{o.project_name ? `Project location: ${o.project_country ? marketName(o.project_country) : "not established"}` : "This is a company-level prospect. Sources may describe awarded work, but no specific named project, project value or timetable is established here."}</p></section>}
            <section className="card p-5" aria-label="Company information"><h2 className="font-bold">Company information</h2><dl className="mt-3 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-xs text-[var(--text-2)]">Business activity</dt><dd className="mt-1">{businessActivity || ""}</dd></div><div><dt className="text-xs text-[var(--text-2)]">Headquarters country</dt><dd className="mt-1">{hqCountry?marketName(hqCountry):""}</dd></div><div><dt className="text-xs text-[var(--text-2)]">Operating country · verified work</dt><dd className="mt-1">{workCountry?marketName(workCountry):""}</dd></div><div><dt className="text-xs text-[var(--text-2)]">Official website</dt><dd className="mt-1 break-all">{enrichment?.domain && enrichment.domainConfirmed ? <a className="inline-flex items-center gap-1 text-[var(--accent-2)] underline" href={`https://${enrichment.domain}`} target="_blank" rel="noreferrer">{enrichment.domain}<ExternalLink size={12} aria-hidden /></a> : ""}</dd></div><div><dt className="text-xs text-[var(--text-2)]">Company size</dt><dd className="mt-1">{detail?.buyer.size_band || ""}</dd></div></dl></section>
            {detail?.buyerInsights ? <details className="card p-4"><summary className="cursor-pointer text-sm font-semibold">Company history & known partners · broader context, not this search&apos;s demand</summary><div className="mt-3"><BuyerHistorySection insights={detail.buyerInsights} buyerName={o.name} /></div></details> : null}
            <section className="rounded-xl border border-[var(--accent)] bg-[var(--accent-soft)] p-4"><div className="flex items-center gap-2"><Mail size={17} aria-hidden /><h2 className="font-bold">Email & meeting progress</h2></div><p className="mt-2 text-sm">{o.sent ? "A demo email was accepted by the provider. Open the conversation to see replies and the meeting step." : "See qualification, automatic sending, replies and meeting status together. Opening this page never sends an email."}</p><button className="btn btn-secondary btn-sm mt-3" onClick={() => selectTab("conversation")}>View conversation & next step →</button></section>
          </> : null}
          {tab === "contacts" ? <>
            <section className="card p-5"><div className="flex items-center gap-2"><Users size={18} aria-hidden /><h2 className="font-bold">Company contacts & optional validation</h2></div><p className="mt-2 text-sm text-[var(--text-2)]">See all available roles, not just {CONTACT_ROLES.find(r => r.id === o.contact_role)?.name || "the preferred role"}. A confirmed role is not a validated email.</p><p className="mt-2 text-sm">{verifiedProspect(o.qualification,o.validated_emails,o.is_sample) ? "This prospect meets the verified CRM criteria." : "Contacts are optional for discovering companies and approved-inbox demos. Review a named contact’s role and validate email to qualify for Validated contacts; a demo email never validates a buyer."}</p></section>
            <SupplyChainExplorer leadId={o.lead_id} rootShortName={buyer.shortName || buyer.name} contactsOnly productScope={{id:o.product_id,name:o.product_name,projectLinked:Boolean(o.project_id)}} />
            <section id="contacts" className="card p-4"><ContactEnrichment opportunityId={o.id} sample={o.is_sample} initial={enrichment} /></section>
          </> : null}
          {tab === "chain" ? <>
            {evidenceView?<WorkspaceChainTables run={o.run_id} company={buyer.companyId}/>:null}
            <section className="card p-5"><div className="flex items-center gap-2"><Network size={18} aria-hidden /><h2 className="font-bold">Subcontractors, suppliers & their contacts</h2></div><p className="mt-2 text-sm text-[var(--text-2)]">Explore the primary company, related companies, tier-2 and tier-3 contacts. Confirmed, likely and possible relationships stay distinct. Unidentified company types are research slots—not discovered buyers.</p><p className="mt-2 text-xs text-[var(--text-2)]">Product scope: {o.product_name}. A supply-chain relationship does not prove current demand or authorise outreach to that company.</p></section>
            {projectDetail ? <SupplyChainSection detail={projectDetail} /> : null}
            <SupplyChainExplorer leadId={o.lead_id} rootShortName={buyer.shortName || buyer.name} productScope={{id:o.product_id,name:o.product_name,projectLinked:Boolean(o.project_id)}} />
          </> : null}
          {tab === "conversation" ? <section id="conversation" className="card p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold">Email, replies & meetings</h2><Link href="/outreach" className="btn btn-secondary btn-sm">View automation & next step</Link></div><p className="mt-2 text-xs text-[var(--text-2)]">Demo delivery only to {demoEmail.recipient || "the configured test inbox"}. Buyer validation remains separate.</p><ConversationTimeline opportunityId={o.id} onChange={()=>router.refresh()} calendarResult={calendarResult} />{drafts.length ? <details className="mt-4 border-t border-[var(--line)] pt-3"><summary className="cursor-pointer text-sm font-semibold">Earlier drafts & separate delivery history ({drafts.length})</summary><ul className="mt-3 space-y-3">{drafts.map(d => <li key={d.id} className="rounded-lg bg-[var(--subtle)] p-3 text-sm"><p className="font-semibold">{d.subject || "Blocked draft"}</p><p className="mt-1 text-xs text-[var(--text-2)]">{formatDateTime(d.created_at)} · {d.delivery_state === "sent" ? `Provider accepted demo email to ${d.delivery_recipient}` : d.campaign_status ? `Automation: ${d.campaign_status}` : d.delivery_state === "failed" ? "Delivery unconfirmed — review before resending" : "Draft / awaiting delivery"}</p><p className="mt-2 whitespace-pre-wrap">{d.body}</p></li>)}</ul></details> : null}<p className="mt-4 text-xs text-[var(--text-2)]">Automatic replies require Resend receiving and Groq; booking requires a connected Calendar and an explicitly selected free slot.</p></section> : null}
          {tab === "activity" ? <section className="card p-5"><h2 className="font-bold">Activity for this product opportunity</h2><ul className="mt-3 space-y-3">{events.length ? events.map(e => <li key={e.id} className="border-l-2 border-[var(--accent)] pl-3 text-sm">{e.body}<p className="mt-1 text-xs text-[var(--text-2)]">{formatDateTime(e.created_at)}</p></li>) : <li className="text-sm text-[var(--text-2)]">No changes yet. Email history is in Email & meetings.</li>}</ul></section> : null}
        </div>
        {(tab === "overview" || tab === "conversation") ? <section className="card mt-4 p-5" aria-label="CRM notes"><h2 className="font-bold">CRM notes & sales ownership</h2><form className="mt-3 flex flex-col gap-3" onSubmit={e => {e.preventDefault(); void patch({summary:summary??o.summary,ownerName,nextAction,followUpAt:followUpAt ? new Date(`${followUpAt}:00Z`).toISOString() : null});}}><div><label htmlFor="opportunity-summary" className="text-sm font-semibold">Summary</label><textarea id="opportunity-summary" value={summary??o.summary} onChange={e => setSummary(e.target.value)} maxLength={4000} className="input mt-1 min-h-24 w-full p-2 font-normal" placeholder="The sales conversation summary updates automatically; you can add notes here." /></div><details><summary className="cursor-pointer text-xs font-semibold text-[var(--text-2)]">Sales owner, next action & manual reminder</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Sales owner<input className="input mt-1 w-full p-2" value={ownerName} onChange={e => setOwner(e.target.value)} maxLength={120} /></label><label className="text-sm font-semibold">Next action<input className="input mt-1 w-full p-2" value={nextAction} onChange={e => setAction(e.target.value)} maxLength={300} /></label><label className="text-sm font-semibold">Manual follow-up reminder (UTC)<input type="datetime-local" className="input mt-1 w-full p-2" value={followUpAt} onChange={e => setFollowUp(e.target.value)} /></label></div><p className="mt-2 text-xs text-[var(--text-2)]">This manual reminder does not control the bounded automatic email sequence.</p></details><button disabled={busy} className="btn btn-primary self-start">{busy ? "Saving…" : "Save CRM notes"}</button></form></section> : null}
      </div>
      <OpportunityRail opportunity={o} buyer={buyer} enrichment={enrichment} points={points} busy={busy} selectTab={selectTab} patch={patch} recipient={demoEmail.recipient} demoOutreach={demoOutreach} />
    </div>
  </div>{evidenceTarget?<EvidenceDrawer key={drawerKey(evidenceTarget)} target={{leadId:evidenceTarget.opportunityId===o.id?o.lead_id:undefined,...evidenceTarget}} onTarget={t=>{setEvidenceTarget(t);const url=new URL(window.location.href);url.searchParams.set('open',drawerKey(t));window.history.replaceState(window.history.state,'',url.pathname+url.search);}} onClose={()=>{setEvidenceTarget(null);const url=new URL(window.location.href);url.searchParams.delete('open');window.history.replaceState(window.history.state,'',url.pathname+url.search);}} returnTo={returnTo}/>:null}</EvidenceProvider>;
}
