"use client";
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { apiJson } from '../api-client';
import type { listFunnelThreads } from '@/mvp/automation/engine';
import { ConversationTimeline } from './conversation-timeline';
import type { FunnelSettings } from './demo-funnel-setup';

type Data={settings:FunnelSettings;threads:Awaited<ReturnType<typeof listFunnelThreads>>};
const LABELS:Record<string,string>={qualifying:'Checking product fit',needs_contact:'Waiting for validated contact',active:'Waiting for Gmail reply',engaged:'Sales conversation',awaiting_calendar:'Meeting requested — connect Google Calendar',awaiting_time:'Waiting for chosen time',meeting_pending:'Creating meeting',meeting_booked:'Meeting booked',stopped:'Stopped',review:'Needs review'};
export function FunnelWorkbench({initial,calendarResult}:{initial:Data;calendarResult?:string}) {
  const [data,setData]=useState(initial);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  useEffect(()=>{let cancelled=false;const poll=async()=>{try{const next=await apiJson<Data>('/api/mvp/automation');if(!cancelled)setData(next);}catch{if(!cancelled)setError('Status refresh failed. Check the local server.');}};const timer=setInterval(()=>{void poll();},10_000);return()=>{cancelled=true;clearInterval(timer);};},[]);
  const act=async(body:object)=>{setBusy(true);setError(null);try{setData(await apiJson<Data>('/api/mvp/automation',{method:'POST',body}));}catch(e){setError(e instanceof Error?e.message:'Could not update automation.');}finally{setBusy(false);}};
  const s=data.settings;const test=data.threads.find(t=>t.mode==='email_test'&&t.recipient===s.recipient);
  return <div className="flex flex-col gap-4">
    <section className="card p-5"><h2 className="text-lg font-bold">Research → email → reply → meeting</h2><p className="mt-2 text-sm text-[var(--text-2)]">New searches automatically check source-backed potential buying companies and start one approved-inbox conversation. Open the same lead workspace for evidence, contacts, email progress and the CRM summary.</p><ol className="mt-4 grid gap-2 text-sm sm:grid-cols-4">{['1. Search for a material','2. Automatic fit check & email','3. Buyer replies in Gmail','4. Agreed meeting booked'].map(step=><li key={step} className="rounded-lg bg-[var(--subtle)] p-3 font-semibold">{step}</li>)}</ol><div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg bg-[var(--subtle)] p-3 text-sm"><p>Automation: <strong>{s.enabled?'on':'paused'}</strong> · Calendar: {s.calendar?'connected':'not connected'} · Delivery only to {s.recipient}</p><Link href="/settings?tab=automation" className="btn btn-secondary btn-sm">Email & Calendar setup</Link></div>{calendarResult==='failed'?<p role="alert" className="mt-2 text-sm text-red-700">Google consent failed. Reconnect in Settings.</p>:null}{s.last_error?<p role="alert" className="mt-2 text-sm text-red-700">{s.last_error}</p>:null}<p className="mt-3 text-xs text-[var(--text-2)]">Partial research keeps its saved companies eligible for independent fit checks. Unknown buyer contacts stay blank. Historical paused conversations are never automatically resumed.</p></section>
    {error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}
    <section className="card p-5" aria-label="Automated conversations"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold">Conversations ({data.threads.filter(t=>t.mode!=='email_test').length})</h2><Link href="/crm" className="btn btn-primary btn-sm">Choose a researched prospect</Link></div>
      {!data.threads.some(t=>t.mode!=='email_test')?<p className="mt-3 text-sm text-[var(--text-2)]">No researched-prospect conversations yet. Open a company in search results, then select Email & meetings.</p>:<ul className="mt-3 divide-y divide-[var(--line)]">{data.threads.filter(t=>t.mode!=='email_test').map(t=><li key={t.id} className="py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link href={`/opportunities/${t.opportunity_id}?tab=conversation`} className="font-bold text-[var(--accent-2)]">{t.company} · {t.product}</Link><p className="mt-1 text-sm">{t.paused?'Paused · ':''}{LABELS[t.state]||t.state}</p><p className="mt-1 text-xs text-[var(--text-2)]">{t.reason}</p>{t.run_id?<p className="mt-1 text-xs text-[var(--text-2)]">Project: {t.project_name||'not identified'} · <Link className="underline" href={`/crm?search=${t.run_id}`}>From search: {t.keyword}</Link></p>:null}</div><Link className="btn btn-secondary btn-sm" href={`/opportunities/${t.opportunity_id}?tab=conversation`}>Open conversation & next step</Link></div>{t.summary?<p className="mt-2 whitespace-pre-wrap text-sm">{t.summary}</p>:null}{t.meet_url?<a href={t.meet_url} className="mt-2 inline-block text-sm font-semibold text-[var(--accent-2)] underline" target="_blank" rel="noreferrer">Open confirmed Google Meet</a>:null}</li>)}</ul>}
    </section>
    <details className="card p-5"><summary className="cursor-pointer font-semibold">Optional inbox-only diagnostic (not a buyer lead)</summary><p className="mt-3 text-sm text-[var(--text-2)]">A separate line-pipe conversation to test email transport without research or verification credits. For the main demo, use a researched prospect above. This diagnostic never enters CRM and has no prospecting follow-ups.</p><button className="btn btn-secondary mt-3" disabled={busy||!s.enabled||!s.ready||!s.worker||Boolean(test)} onClick={()=>void act({action:'start_email_test',confirmedRecipient:s.recipient,productId:'line-pipe'})}>Start live inbox diagnostic</button>{test&&['active','engaged'].includes(test.state)?<button className="btn btn-secondary mt-3 ml-2" disabled={busy||!s.enabled||test.paused} onClick={()=>void act({action:'send_seller_test_intro',threadId:test.id,confirmedRecipient:s.recipient})}>Send corrected diagnostic introduction (once)</button>:null}{test?<ConversationTimeline testThreadId={test.id}/>:null}</details>
  </div>;
}
