"use client";
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { apiJson } from '../api-client';
import type { listFunnelThreads } from '@/mvp/automation/engine';
import { ConversationTimeline } from './conversation-timeline';
import type { FunnelSettings } from './demo-funnel-setup';

type Data={settings:FunnelSettings;threads:Awaited<ReturnType<typeof listFunnelThreads>>};
const LABELS:Record<string,string>={qualifying:'Checking product fit',needs_contact:'Waiting for validated contact',active:'Introduction / follow-up workflow',engaged:'Sales conversation',awaiting_calendar:'Meeting requested — connect Google Calendar',awaiting_time:'Waiting for chosen time',meeting_pending:'Creating meeting',meeting_booked:'Meeting booked',stopped:'Stopped',review:'Needs review'};
export function FunnelWorkbench({initial,calendarResult}:{initial:Data;calendarResult?:string}) {
  const [data,setData]=useState(initial);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  useEffect(()=>{let cancelled=false;const poll=async()=>{try{const next=await apiJson<Data>('/api/mvp/automation');if(!cancelled){setData(next);setError(null);}}catch{if(!cancelled)setError('Status refresh failed. Check your connection; the last known status is shown.');}};const timer=setInterval(()=>{void poll();},10_000);return()=>{cancelled=true;clearInterval(timer);};},[]);
  const act=async(body:object)=>{setBusy(true);setError(null);try{setData(await apiJson<Data>('/api/mvp/automation',{method:'POST',body}));}catch(e){setError(e instanceof Error?e.message:'Could not update automation.');}finally{setBusy(false);}};
  const s=data.settings;const test=data.threads.find(t=>t.mode==='email_test'&&t.recipient===s.recipient);
  return <div className="flex flex-col gap-4">
    <section className="card p-5" data-tour="automation-health" aria-label="Automation status">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{s.enabled&&s.ready&&s.worker?'Automation is running':'Automation needs attention'}</h2><p className="mt-1 text-sm text-[var(--muted)]">New searches → qualified lead → introduction → reply → agreed meeting</p></div><Link href="/settings?tab=automation" className="btn btn-secondary btn-sm">Manage connections</Link></div>
      <dl className="mt-4 grid gap-4 rounded-lg bg-[var(--subtle)] p-4 text-sm sm:grid-cols-3"><div><dt className="text-xs text-[var(--muted)]">Salesperson (sender)</dt><dd className="mt-1 font-semibold">{s.seller.name}{s.seller.company?` · ${s.seller.company}`:''}</dd></div><div><dt className="text-xs text-[var(--muted)]">Approved demo inbox (receiver)</dt><dd className="mt-1 break-all font-semibold">{s.recipient}</dd></div><div><dt className="text-xs text-[var(--muted)]">Google Calendar</dt><dd className="mt-1 font-semibold">{s.calendar?'Connected':'Not connected · consent needed'}</dd></div></dl>
      <p className="mt-3 text-xs text-[var(--muted)]">Buyers are the researched companies below. Your demo inbox receives their simulated conversations; no buyer is emailed. Up to {s.prospectsPerSearch} new qualified {s.prospectsPerSearch===1?'company':'companies'} per search. Opening a page never starts a new email.</p>
      {calendarResult==='failed'?<p role="alert" className="mt-2 text-sm text-red-700">Google consent failed. Reconnect in Settings.</p>:null}
      {s.last_error||s.configError?<p role="alert" className="mt-3 text-sm text-red-700">{s.last_error||s.configError}</p>:null}
      {!s.enabled||!s.ready||!s.worker?<p className="mt-3 text-sm text-amber-800">Delivery is not ready. Check connections and the email worker before starting a search.</p>:null}
    </section>
    {error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}
    <section className="card p-5" data-tour="automation-conversations" aria-label="Automated conversations"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold">Conversations ({data.threads.filter(t=>t.mode!=='email_test').length})</h2><Link href="/crm" className="btn btn-secondary btn-sm">View leads</Link></div>
      {!data.threads.some(t=>t.mode!=='email_test')?<p className="mt-3 text-sm text-[var(--text-2)]">No conversations yet. Run a new material search with automation ready. Eligible companies are checked automatically; watch a lead’s Email & meetings tab for the actual sending status.</p>:<ul className="mt-3 divide-y divide-[var(--line)]">{data.threads.filter(t=>t.mode!=='email_test').map(t=><li key={t.id} className="py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link href={`/opportunities/${t.opportunity_id}?tab=conversation`} className="font-bold text-[var(--accent-2)]">{t.company} · {t.product}</Link><p className="mt-1 text-sm">{t.paused?'Paused · ':''}{LABELS[t.state]||t.state}</p><p className="mt-1 text-xs text-[var(--text-2)]">{t.reason}</p>{t.run_id?<p className="mt-1 text-xs text-[var(--text-2)]">Project: {t.project_name||'not identified'} · <Link className="underline" href={`/crm?run=${t.run_id}`}>From search: {t.keyword}</Link></p>:null}{t.why?<p className="mt-2 max-w-3xl text-xs leading-5 text-[var(--text-2)]"><strong>Why this lead:</strong> “{t.why.slice(0,220)}{t.why.length>220?'…':''}”{t.application?<span className="block">{t.application}</span>:null}{t.run_id?<Link className="font-semibold text-[var(--accent-2)] underline" href={`/crm?run=${t.run_id}&open=${t.opportunity_id}`}>See evidence</Link>:null}</p>:null}</div><Link className="btn btn-secondary btn-sm" href={`/opportunities/${t.opportunity_id}?tab=conversation`}>View conversation</Link></div>{t.summary?<details className="mt-2 text-sm"><summary className="cursor-pointer text-[var(--muted)]">Conversation summary</summary><p className="mt-2 whitespace-pre-wrap">{t.summary}</p></details>:null}{t.meet_url?<a href={t.meet_url} className="mt-2 inline-block text-sm font-semibold text-[var(--accent-2)] underline" target="_blank" rel="noreferrer">Open confirmed Google Meet</a>:null}</li>)}</ul>}
    </section>
    <details className="card p-5"><summary className="cursor-pointer font-semibold">Optional inbox-only diagnostic (not a buyer lead)</summary><p className="mt-3 text-sm text-[var(--text-2)]">A separate line-pipe conversation to test email transport without research or verification credits. For the main demo, use a researched prospect above. This diagnostic never enters CRM and has no prospecting follow-ups.</p><button className="btn btn-secondary mt-3" disabled={busy||!s.enabled||!s.ready||!s.worker||Boolean(test)} onClick={()=>void act({action:'start_email_test',confirmedRecipient:s.recipient,productId:'line-pipe'})}>Start live inbox diagnostic</button>{test&&['active','engaged'].includes(test.state)?<button className="btn btn-secondary mt-3 ml-2" disabled={busy||!s.enabled||test.paused} onClick={()=>void act({action:'send_seller_test_intro',threadId:test.id,confirmedRecipient:s.recipient})}>Send corrected diagnostic introduction (once)</button>:null}{test?<ConversationTimeline testThreadId={test.id}/>:null}</details>
  </div>;
}
